hello_world:
	go run hello_world.go

pointer:
	go run pointer.go

function:
	go run function.go

swap:
	go run swap.go

immediate_func:
	go run immediate_func.go

array:
	go run array.go

slice:
	go run slice.go
